name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: pip install -e .
      - run: pip install -r requirements-lock.txt
      - run: python cute.py test
